### ISSUE TITLE
Options misses the property 'exposes'

### ISSUE THREAD

**Issue by bigfuture-test** [80percent/rails-template#29]
Got following error after fresh start:

```
Failed to compile.

./node_modules/jquery/dist/jquery.js (./node_modules/expose-loader/dist/cjs.js!./node_modules/jquery/dist/jquery.js)
Module build failed (from ./node_modules/expose-loader/dist/cjs.js):
ValidationError: Invalid options object. Expose Loader has been initialized using an options object that does not match the API schema.
 - options misses the property 'exposes'. Should be:
   non-empty string | object { globalName, moduleLocalName?, override? } | [non-empty string | object { globalName, moduleLocalName?, override? }, ...] (should not have fewer than 1 item)
    at validate (.../node_modules/schema-utils/dist/validate.js:96:11)
    at Object.loader (.../node_modules/expose-loader/dist/index.js:24:28)
```

Any idea on how to fix?

**Comment by encoreshao** [comment]
@sushil-bigfuture  please do some updates in `/config/webpack/environment.js`, hope it will help you.

**Before**

```
    environment.loaders.append('expose', {
        test: require.resolve('jquery'),
        use: [{
            loader: 'expose-loader',
            options: '$'
        }, {
            loader: 'expose-loader',
            options: 'jQuery',
        }]
    })
```

**After**
```
  environment.loaders.append('expose', {
    test: require.resolve('jquery'),
    use: [
      {
        loader: "expose-loader",
        options: {
          exposes: ["$", "jQuery"]
        }
      }
    ]
  })
```

**Comment by windy** [comment]
maybe the new version webpacker cause this problem?

**Comment by marvinthepa** [comment]
> **After**
> 
> ```
>   environment.loaders.append('expose', {
>     test: require.resolve('jquery'),
>     use: [
>       {
>         loader: "expose-loader",
>         options: {
>           exposes: ["$", "jQuery"]
>         }
>       }
>     ]
>   })
> ```

Does not work for me:

```
ERROR in ./node_modules/jquery/dist/jquery.js (./node_modules/babel-loader/lib!./node_modules/expose-loader/dist/cjs.js!./node_modules/jquery/dist/jquery.js)
Module build failed (from ./node_modules/expose-loader/dist/cjs.js):
ValidationError: Invalid options object. Expose Loader has been initialized using an options object that does not match the API schema.
 - options misses the property 'exposes'. Should be:
   non-empty string | object { globalName, moduleLocalName?, override? } | [non-empty string | object { globalName, moduleLocalName?, override? }, ...] (should not have fewer than 1 item)
```

**Comment by windy** [comment]
fixed here:

https://github.com/dao42/rails-template/commit/3425f87ecf860747440a32545d79ba533c98144f#diff-81b1e5edffefd1238a8108b39fcc4de127de7020638a7722ebb9a8d1a9c90ce5R74
